#!/bin/sh
set -e

if ! ls /etc/ssh/ssh_host_* 1> /dev/null 2>&1; then
    ssh-keygen -A
fi

if ls /root/.ssh/authorized_keys 1> /dev/null 2>&1; then
  chown root:root /root/.ssh/authorized_keys
  chmod 600 /root/.ssh/authorized_keys
fi

if ls /opt/veeam/transport/scripts/veeamtransport.service 1> /dev/null 2>&1; then
   systemctl enable /opt/veeam/transport/scripts/veeamtransport.service
fi

#systemctl status
#systemctl start sshd 

#service veeamservice start

exec "$@"
