#!/bin/sh
set -e

if ! ls /etc/ssh/ssh_host_* 1> /dev/null 2>&1; then
    ssh-keygen -A
fi

if ls /root/.ssh/authorized_keys 1> /dev/null 2>&1; then
  chown root:root /root/.ssh/authorized_keys
  chmod 600 /root/.ssh/authorized_keys
fi

#service veeamservice start

exec "$@"
