#!/bin/sh
set -e

echo "Check keygen"
if ! ls /etc/ssh/ssh_host_* 1> /dev/null 2>&1; then
    ssh-keygen -A
fi

echo "Check authorized keys"
if ls /root/.ssh/authorized_keys 1> /dev/null 2>&1; then
  chown root:root /root/.ssh/authorized_keys
  chmod 600 /root/.ssh/authorized_keys
fi

echo "Check transport service"
if ls /opt/veeam/transport/scripts/veeamtransport.service 1> /dev/null 2>&1; then
   if ! ls /etc/systemd/system/veeamtransport.service 1> /dev/null 2>&1; then
   	systemctl enable /opt/veeam/transport/scripts/veeamtransport.service
   fi 
fi

if ! ls /etc/tmpfiles.d/systemd-nologin.conf 1> /dev/null 2>&1; then
  ln -sf /dev/null /etc/tmpfiles.d/systemd-nologin.conf
fi

systemctl enable veeamservice

/lib/systemd/systemd

exec "$@"

